<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-DK4JNSP" failures="1" tests="8" name="Personal loan" time="0.125" errors="0" timestamp="2022-07-13T21:33:50 EDT">
  <testcase classname="Test.Day1" name="demo" time="0.008"/>
  <testcase classname="Test.Day1" name="thirdTest" time="0.008"/>
  <testcase classname="Test.Day2" name="listerntest1" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day2.listerntest1(Day2.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- listerntest1 -->
  <testcase classname="Test.Day2" name="ploan" time="0.003"/>
  <testcase classname="Test.Day3" name="apilogincar" time="0.002"/>
  <testcase classname="Test.Day3" name="apilogincar" time="0.003"/>
  <testcase classname="Test.Day3" name="apilogincar" time="0.004"/>
  <testcase classname="Test.Day3" name="weblogincar" time="0.008"/>
  <testcase classname="Test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
  <testcase classname="Test.Day3" name="mobilelogincar" time="0.0">
    <ignored/>
  </testcase> <!-- mobilelogincar -->
</testsuite> <!-- Personal loan -->
